#ifndef PORCODIO_H
#define PORCODIO_H

#include <stdio.h>
#include <stdlib.h>
#include <time.h>

#define NUMERO_BESTEMMIE sizeof(bestemmie)/sizeof(bestemmie[0])

static const char* bestemmie[] = {
	"dio fa",
	"porco dio",
	"dio casareccio",
	"dio bocchinaro",
	"dio scemo",
	"puttana eva",
	"dio energumeno",
	"dio zingaro",
	"dio criminale",
	"dio crocifisso male",
	"madonna infinocchiata",
	"madonna sodomizzata",
	"dio data structure",
	"madonna laida",
	"dio rasputin",
	"madonna imburrata",
	"dio cornetto algida",
	"madonna sburrata",
	"dio napolanzi",
	"dio cucitore di scarpe sottopagato",
	"madonna impeciata e impiumata",
	"dio cpu bruciata",
	"madonna groupie assassinata",
	"dio lezzo",
	"dio affogato nella merda ",
	"dio aguzzino",
	"dio ammuffito",
	"dio gallo cedrone",
	"dio appassito",
	"dio pederasta",
	"dio appestato",
	"dio asociale",
	"dio crogiolo",
	"dio tappo di sughero",
	"dio assatanato",
	"dio ano sfondato",
	"dio asmr",
	"dio carciofo mutante",
	"dio avvelenato",
	"dio bastardo",
	"dio bastonato",
	"dio escamotage",
	"dio becchino",
	"dio caprone da monta con sotto la madonna",
	"dio 124 messaggi",
	"dio transfobico",
	"dio bestia",
	"dio piccione viaggiatore",
	"dio boia",
	"dio caldarroste",
	"dio brufoloso",
	"dio vibo valentia",
	"dio metamorfico",
	"madonna impiccata",
	"dio cagnaccio",
	"dio cavalca mignotte",
	"dio camperista balsamico ",
	"dio e.t.",
	"dio cancro",
	"madonna in agrodolce",
	"dio cane",
	"dio cane bastardo",
	"madonna idrovolante",
	"dio elettricista fuori fase",
	"madonna impestata cagna",
	"dio quella vacca sozza lurida puttana sozza impestata vergine",
	"madonna incarnita",
	"dio cannibale",
	"dio castrato",
	"dio checca ",
	"dio ciclista senza sellino ",
	"dio cleziano ",
	"dio contrabbandiere ",
	"dio cornuto",
	"dio incornato tra le chiappe",
	"dio ecclesiastico ",
	"dio evasore fiscale ",
	"dio fagiano",
	"madonna infibulata",
	"dio falsario",
	"dio falso",
	"dio frocione",
	"dio guerrafondaio",
	"dio impestato",
	"dio improbo",
	"dio friggitrice incrostata",
	"dio inculato",
	"dio pagliaccio merda",
	"dio ladro",
	"dio kamikaze musulmano",
	"dio lebbroso",
	"dio lurido",
	"dio mafioso ",
	"dio maiale",
	"madonna ipotonica",
	"dio morto de fame",
	"dio omertoso ",
	"dio pagliaccio",
	"dio papa ",
	"dio pezzente",
	"madonna inverosimile maiala",
	"dio piegato dalla fica ",
	"dio pompinaro",
	"dio scopettone",
	"dio porco",
	"dio cinciallegra",
	"dio puttaniere",
	"dio spacciatore ",
	"dio sporco",
	"dio squallido ",
	"madonna isotonica",
	"dio stronzo",
	"dio sudicio",
	"dio superdotato come si gira si incula ",
	"dio tamarro",
	"dio terrorista",
	"dio truffatore",
	"dio percosso con un martello pneumatico",
	"dio truzzo",
	"dio vaffanculo",
	"dio savoiardo affogato nel caffè",
	"dio antiporto",
	"dio verginello",
	"dio mostro di lochness",
	"dio simporto",
	"dio zerbino",
	"dio tavernello",
	"dio lebbroso",
	"porco dio",
	"porno dio",
	"dio merda",
	"diocane",
	"diomerda",
	"madonna assassina",
	"madonna bandita",
	"dio slittino",
	"madonna bastarda",
	"dio netturbino",
	"madonna battona",
	"dio serpentiforme",
	"madonna bocchinara",
	"dio minestrone",
	"madonna capra",
	"dio Anassimandro",
	"madonna cornuta",
	"dio massa di merda",
	"madonna cretina",
	"madonna crocifissa",
	"dio travertino",
	"dio minchia assoluta",
	"madonna diavola",
	"madonna pellicola da 8mm",
	"dio segaiolo",
	"madonna fricchettona",
	"madonna ladra",
	"dio spiaggia, porco per ogni granello de sabbia",
	"madonna istrice",
	"madonna indiavolata",
	"madonna lardona",
	"madonna pantegana",
	"madonna lebbrosa",
	"dio lestofante",
	"madonna lurida",
	"madonna koala",
	"madonna maiala",
	"dio stra can madonna nel forno",
	"madonna maledetta",
	"dio licantropo",
	"madonna mignotta ",
	"madonna nana radioattiva",
	"dio proletario",
	"madonna schifosa letamaia",
	"madonna pompinara",
	"madonna missile testata nucleare diretto verso il paradiso",
	"madonna putrida",
	"dio peretta",
	"dio sborrata",
	"madonna putrida vacca",
	"dio masticato da san pietro",
	"dio pungitopo",
	"madonna masturbatrice di cavalli",
	"madonna lontra schiacciata",
	"madonna puttana",
	"dio schermata blu di windows",
	"madonna lacerata",
	"dio nazista e i santi SS",
	"dio cotechino",
	"madonna mattone",
	"madonna scoreggiona",
	"dio pattume stagnante",
	"madonna orba che cade dalle scale",
	"madonna scrofa in calore",
	"dio elemosina",
	"madonna sorca",
	"madonna strozzina",
	"madonna maiala riproduzione",
	"madonna lucidata con la spazzola d'acciaio",
	"dio taralluccio affogato nel vino",
	"madonna stuprata",
	"madonna succhiacazzi",
	"dio coca sgasata",
	"dio schifoso di merda",
	"madonna trivellata",
	"dio liofilizzato",
	"madonna troia",
	"madonna vigliacca",
	"dio ladro de galline",
	"madonna zoccola",
	"dio acido nitrico",
	"madonna mazinga",
	"madonna zoccola da gara",
	"dio stoccafisso",
	"mannaggia la madonna",
	"porca madonna",
	"puttana madonna",
	"puttana la madonna",
	"madonna discord",
	"dio frocio",
	"dio cappuccio",
	"dioaffogatonellamerda",
	"dio coglioni frantumati",
	"dio loffa incendaria",
	"dio maiale strozzato dalle ghiande",
	"dio mammalucco castrato",
	"dio rugginoso",
};

static void bestemmia()
{
    srand(time(NULL));

    puts(bestemmie[rand()%NUMERO_BESTEMMIE]);
}

#endif // PORCODIO_H
